runtime: python39 # Specify the Python version. Adjust according to your compatibility.
entrypoint: gunicorn -b :$PORT main:app # Specifies the command that runs your application. 'main' should be replaced with the name of your Python file without the '.py' if it's not named 'main.py'.
env: standard # Specifies that you are using the standard environment.

# You can choose to use automatic scaling, basic scaling, or manual scaling by uncommenting one of the following sections.
# This example uses automatic scaling.
runtime_config:
  python_version: 3
manual_scaling:
  instances: 1 # Optional. Specifies the minimum number of instances.
  

# Optional handlers section for configuring URL handlers and static files.
handlers:
  - url: /.* # This configuration directs all URLs to your main application.
    script: auto # Required for Python 3.7 and later in the standard environment.
