runtime: python39  # Specify the Python runtime version
entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn as the HTTP server, with the environment variable PORT

env: standard  # Use the standard environment
instance_class: F1  # Specify the instance class (F1 is the smallest available)

handlers:
- url: /.*  # Route all traffic to the application
  script: auto
